### ISSUE TITLE
FW for Loongson-LS2C5LE

### ISSUE THREAD

**Issue by alexxy** [loongson/Firmware#10]
Hi is it possible to get fw compatible with mainline linux for that board?

```
BIOS Information
        Vendor: Loongson
        Version: Loongson-UDK2018-V1.6.2-8W
        Release Date: 06/20/2022
        ROM Size: 4 MB
        Characteristics:
                PCI is supported
                BIOS is upgradeable
                Boot from CD is supported
                Selectable boot is supported
                BIOS ROM is socketed
                Serial services are supported (int 14h)
                USB legacy is supported
                UEFI is supported
        BIOS Revision: 1.6

Handle 0x0002, DMI type 1, 27 bytes
System Information
        Manufacturer: LOONGSON
        Product Name: LOONGSON T100 T2208A
        Wake-up Type: Power Switch
        SKU Number: Not Specified
        Family: Not Specified

Handle 0x0003, DMI type 2, 17 bytes
Base Board Information
        Manufacturer: LOONGSON
        Product Name: Loongson-LS2C5LE
        Version: LS2C5LE 
        Features:
                Board is a hosting board
                Board is replaceable
        Location In Chassis: Not Specified
        Chassis Handle: 0x0000
        Type: Motherboard
        Contained Object Handles: 0

```

**Comment by kilaterlee** [comment]
Will upload later, might be a few weeks.

Thanks,
Chao
--------

**Comment by MarsDoge** [comment]
> Hi is it possible to get fw compatible with mainline linux for that board?
> 
> ```
> BIOS Information
>         Vendor: Loongson
>         Version: Loongson-UDK2018-V1.6.2-8W
>         Release Date: 06/20/2022
>         ROM Size: 4 MB
>         Characteristics:
>                 PCI is supported
>                 BIOS is upgradeable
>                 Boot from CD is supported
>                 Selectable boot is supported
>                 BIOS ROM is socketed
>                 Serial services are supported (int 14h)
>                 USB legacy is supported
>                 UEFI is supported
>         BIOS Revision: 1.6
> 
> Handle 0x0002, DMI type 1, 27 bytes
> System Information
>         Manufacturer: LOONGSON
>         Product Name: LOONGSON T100 T2208A
>         Wake-up Type: Power Switch
>         SKU Number: Not Specified
>         Family: Not Specified
> 
> Handle 0x0003, DMI type 2, 17 bytes
> Base Board Information
>         Manufacturer: LOONGSON
>         Product Name: Loongson-LS2C5LE
>         Version: LS2C5LE 
>         Features:
>                 Board is a hosting board
>                 Board is replaceable
>         Location In Chassis: Not Specified
>         Chassis Handle: 0x0000
>         Type: Motherboard
>         Contained Object Handles: 0
> ```

At present, the LS2C5LE(prebeta9) version can start the mainline linux normally, we still probably need three days for stability verification, soon, thanks for the support -.-
