### ISSUE TITLE
使用串口进入efi的shell和grub菜单

### ISSUE THREAD

**Issue by lshw** [loongson/Firmware#107]
我这里有一块 3A5000-7A2000-EVB，通过串口， 没法进入efi的命令行， grub的菜单也不能在串口显示出来，
grub的配置:
GRUB_TERMINAL_INPUT="console serial"
GRUB_TERMINAL_OUTPUT="gfxterm serial"
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1" 

在x86的机器， 串口是可以显示出grub菜单的。

我该如何操作？

**Comment by lshw** [comment]
UDK2018_3A5000-7A2000_Desktop_EVB_V4.0.05569-stable202308_rel.fd 这个不行，
降级到UDK2018_3A5000-7A2000_Desktop_EVB_V4.0.05536-Prestable202308_dbg.fd 后

串口可以正常进入grub菜单了。

**Comment by xry111** [comment]
刷 dbg 版本即可，rel 版本没有串口输出。
