### ISSUE TITLE
Update Virtual Machine firmware for QEMU 9.0

### ISSUE THREAD

**Issue by driver1998** [loongson/Firmware#108]
In QEMU 9.0 code.fd and vars.fd are now both loaded as flash: https://github.com/qemu/qemu/commit/c6e9847fc4becba561c631c4505e3b05d4926184.

The corresponding EDK2 updates are merged as https://github.com/tianocore/edk2-platforms/commit/7f42d4034c8f4266da691df69dce18234f752cb4. But the firmware images in this repo are not updated. 

Trying to use NVRAM with firmware images here and QEMU 9.0 will result in NVRAM being written to code.fd, thus bricking the VM.

**Comment by lixianglai** [comment]
Firmware update:
https://github.com/loongson/Firmware/pull/109
