### ISSUE TITLE
固件文件是不是应该添加一个校验文件

### ISSUE THREAD

**Issue by haowuge** [loongson/Firmware#24]
固件文件是不是应该添加一个校验文件，避免文件下载的时候存在数据不完全情况
比如 AAAAAA.SHA256

**Comment by xen0n** [comment]
Good idea!

**Comment by MarsDoge** [comment]
> 固件文件是不是应该添加一个校验文件，避免文件下载的时候存在数据不完全情况 比如 AAAAAA.SHA256

我们的确有这个计划并且在服务器产品上已经初步做了刷新校验逻辑，之后我们会再次完善它并适配到所有产品上；
感谢您的宝贵意见！😄

**Comment by MarsDoge** [comment]
> 固件文件是不是应该添加一个校验文件，避免文件下载的时候存在数据不完全情况 比如 AAAAAA.SHA256

我们有计划添加刷写时文件校验功能，并且在服务器产品上已经初步使用MD5的方式针对刷写请求进行文件完整性校验，之后我们会再次完善它并**尽快适配到所有产品**上,可能也会转到sha256的方式进行刷写时完整性校验； 
感谢您的宝贵意见！😄

**Comment by xry111** [comment]
好像缺了最新的 3A5000-7A2000-EVB 的 sha256。

我有点想弄个 GitHub action 自动算 sha256……
