### ISSUE TITLE
A2101 - Can not be upgraded using the upgrade tool in BIOS menu

### ISSUE THREAD

**Issue by bu3w** [loongson/Firmware#3]
When I try to upgrade the BIOS from the internal upgrade tool in BIOS v3.25, the following message be shown.
"不支持的固件版本"
BTW, the size of beta8 file is 4128768 bytes. but the size of v3.25 is 4194304 bytes.

The current BIOS file (UDK2018-LoongArch-A2101-pre-beta8.fd) is not signed version.
I have to write the file using the external tool into the flash chip. correct?

**Comment by xen0n** [comment]
You could enter the UEFI Shell and use `spi -u` to flash. Type `spi` to get usage.

**Comment by bu3w** [comment]
Thank you. it works for me.
"help spi" for get usage.
"spi -u xxx.fd" for upgrade the firmware.
