### ISSUE TITLE
LM-LS3B5000-7A1000-2w-V01-server_A2114 - Firmware needed

### ISSUE THREAD

**Issue by KatyushaScarlet** [loongson/Firmware#5]
Does anyone have the new firmware for this board?
It is named as **LM-LS3B5000-7A1000-2w-V01-server_A2114**.
On both CPUs there is a "Primitive sample" sign.
Athough the CPU shows **LS3A5000** on the package, it is actually recognized as **loongson-3B5000** in the BIOS, and it has a frequency of **1.6Ghz**.

![20220303160753](https://user-images.githubusercontent.com/24467495/175000817-58efe891-fe2e-4775-bd64-145ada46b0fe.jpg)
![20220303160739](https://user-images.githubusercontent.com/24467495/175000878-66b8e6ce-8fc3-4ddd-bd9e-c433a16143a2.jpg)
![20220303160658](https://user-images.githubusercontent.com/24467495/175001680-fa15f803-2aea-4abe-919c-c99ab7289aa4.jpg)
![20220303160943](https://user-images.githubusercontent.com/24467495/175000929-916fc12c-dd15-49c5-b22b-473afb6d660f.jpg)
![20220303161657](https://user-images.githubusercontent.com/24467495/175000972-179c4120-4495-4556-a32f-5384cd850bf3.jpg)
![20220303165639](https://user-images.githubusercontent.com/24467495/175001012-d9208ecc-e7c8-47dc-b537-e3ca4821e114.jpg)

**Comment by kilaterlee** [comment]
We have no plan support 3B5000 platform now, maybe one day in the future, we can support them, but there is no more energy now, sorry. 
**Note that primitive sample chips are not recommended for production ENV.**
