### ISSUE TITLE
3a5000 7a2000 evb 请求支持HMA82GR7CJR8N-XN RDIMM

### ISSUE THREAD

**Issue by FanFansfan** [loongson/Firmware#60]
目前固件在write leveling时发生错误。
![telegram-cloud-document-5-6280446319488142466](https://github.com/loongson/Firmware/assets/15124392/428b46fb-3c4f-4d1c-b22b-8ff90e15863d)
查看memconfig，发现RDIMM应该是被支持的，至少没有直接报错。
![telegram-cloud-photo-size-5-6280446319944382097-y](https://github.com/loongson/Firmware/assets/15124392/c001fd0b-6f58-4065-a25d-feee47164e5a)

如果有需要，我可以把SPD参数读出来。

**Comment by MarsDoge** [comment]
PC类产品由于主板设计支持UDIMM，不支持RDIMM，服务器产品支持RDIMM.
