### ISSUE TITLE
刷新 UDK2018_3A5000-7A2000_Desktop_EVB_V4.0.05429-stable202302_rel.fd 成功后，U盘安装 Loongnix-20.5.livecd.loongarch64.iso 花屏

### ISSUE THREAD

**Issue by dingymm** [loongson/Firmware#61]
天创者 L5A2 刷新 UDK2018_3A5000-7A2000_Desktop_EVB_V4.0.05429-stable202302_rel.fd 成功后，U盘安装 Loongnix-20.5.livecd.loongarch64.iso 花屏

选择 安装选项后，入下图所示

**Comment by dingymm** [comment]
![image](https://github.com/loongson/Firmware/assets/31890543/b9d0d240-6572-46d7-b7b7-5e6dd535d284)

**Comment by MarsDoge** [comment]
@dingymm 请验证https://github.com/loongson/Firmware/blob/3e33268a0bc86f39715141304e2a112415fb3b3b/5000Series/PC/3A5000-7A2000-EVB/UDK2018_3A5000-7A2000_Desktop_EVB_V4.0.05536-Prestable202308_dbg.fd

**Comment by dingymm** [comment]
感谢回复~已经刷新好了。内容大更新啊！
![144df2f4181746b04c019966b09bd92](https://github.com/loongson/Firmware/assets/31890543/7c555234-05f7-4f8a-afd4-9240e7a6d0f2)
但是引导安装程序还是
![668008757e02c17acc36fa3ed4f3d82](https://github.com/loongson/Firmware/assets/31890543/4834b76c-7f96-4b28-b1aa-3c8b085b923b)
其他的情况，
1、我没有安装独立显卡，2、内存已经更换了几种，目前是8g单根的英睿达，插在靠近cpu的位置，3，u盘是用rufus写入的。

**Comment by dingymm** [comment]
问题找到了！~！！我分别用hdmi在两台显示器dell的2417 1920x1200 和 飞利浦2K 都是一样的问题。然后找出一台 优派va2232 19寸的 vga显示器 用vga连接，可以显示出画面了。

**Comment by dingymm** [comment]
后面我又测试，用HDMI口，接这台可以用的优派va2232，一样花屏。所以怀疑是主板HDMI接口输出部分的问题。希望官方可以解决。
