### ISSUE TITLE
天创者

### ISSUE THREAD

**Issue by lshw** [loongson/Firmware#64]
刷了新的rom, 南桥风扇不转， 天创者的V1.5和V1.4有区别吗？看图片是1.4, 我的板子是1.5,

**Comment by lshw** [comment]
flashrom程序用CH341A_SPI 写新的rom, 启动时南桥风扇不转，串口无输出
刷回原来的ROM,南桥风扇可以转动， 但屏幕黑屏，串口输出如下， 请问我该怎么办？
                                                                                                                                                             
base 1518: 0000000000000000                                                                                                                                                                    
mask 1598: 0000000000000000                                                                                                                                                                    
mmap 1618: 0000000000000000                                                                                                                                                                    
base 1520: 0000000000000000                                                                                                                                                                    
mask 15a0: 0000000000000000                                                                                                                                                                    
mmap 1620: 0000000000000000                                                                                                                                                                    
base 1528: 0000000000000000                                                                                                                                                                    
mask 15a8: 0000000000000000                                                                                                                                                                    
mmap 1628: 0000000000000000                                                                                                                                                                    
base 1530: 0000000000000000                                                                                                                                                                    
mask 15b0: 0000000000000000                                                                                                                                                                    
mmap 1630: 0000000000000000                                                                                                                                                                    
base 1538: 0000000000000000                                                                                                                                                                    
mask 15b8: 0000000000000000                                                                                                                                                                    
mmap 1638: 0000000000000000                                                                                                                                                                    
Gmem init done!                                                                                                                                                                                
syn0 Mac is valid, Mac address:                                                                                                                                                                
38:F7:CD:C4:2C:9F                                                                                                                                                                              
Error::: PHY not responding Busy bit dIdnot get cleared !!!!!!                                                                                                                                 
Error::: PHY not responding Busy bit dIdnot get cleared !!!!!!                                                                                                                                 
Error::: PHY not responding Busy bit dIdnot get cleared !!!!!!                                                                                                                                 
Error::: PHY not responding Busy bit dIdnot get cleared !!!!!!                                                                                                                                 
syn1 Mac is invalid, Mac address:                                                                                                                                                              
FF:FF:FF:FF:FF:FF                                                                                                                                                                              
now get a new mac                                                                                                                                                                              
syn1 New Mac address:                                                                                                                                                                          
0E:99:66:39:CF:C8                                                                                                                                                                              
syn1 Mac is invalid, Please update spi mac address                                                                                                                                             
HdaMemAddr  = 0x80000E0041000000                                                                                                                                                               
CorbVirAddr = 0x90000000902FF000                                                                                                                                                               
CorbPhyAddr = 0x902FF000                                                                                                                                                                       
Codec Vendor Id = 0x10EC0897                                                                                                                                                                   
[HdaFix]: Fix the Codec Subsystem ID: 0x10EC7A07                                                                                                                                               
SmartFan Init, MinRpm:5000 ,MaxRpm;10000                                                                                                                                                       
Ls7A1000 Chipset initialize done.                                                                                                                                                              
FirstTimeWakeUpAp: func 0x90000000901A9DB4, CpuMpData 0x90000000902FE000                                                                                                                       
MpInitLib: Find 4 processors in system.                                                                                                                                                        
Cpu Frequency: 2500 .                                                                                                                                                                          
[DcPhyInit:129:DcPhyInitFunc]Enter.                                                                                                                                                            
[DcPhyInit:158:DcPhyInitFunc]Leave.                                                                                                                                                            
[DcPhyInit:129:DcPhyInitFunc]Enter.                                                                                                                                                            
[DcPhyInit:158:DcPhyInitFunc]Leave.                                                                                                                                                            
Dc Phy Init Done.                                                                                                                                                                              
PublishPeiMemory: MemoryBase=90000000C0C20000, MemorySize=995 MB                                                                                                                               
PeiInstallPeiMemory MemoryBegin 0x90000000C0C20000, MemoryLength 0x3E3E0000                                                                                                                    
Publish Memory Initialize done.                                                                                                                                                                
Start GetCapsuleDataAndToHob !!!                                                                                                                                                               
Unlock Scache Windows first                                                                                                                                                                    
flush scache to unlock scache for 3a                                                                                                                                                           
punlockbase 9000000090000000                                                                                                                                                                   
FlashDxeFvBase:0x800000001C170000 MemDxeFvBase:0x90000000C00C0000 FlashDxeFvSize:0x280000 FlashDxeFvOffset:0x170000                                                                            
Before memcpy                                                                                                                                                                                  
After memcpy                                                                                                                                                                                   
Platform PEI Firmware Volume Initialization                                                                                                                                                    
Install PPI: 49EDB1C1-BF21-4761-BB12-EB0031AABB39                                                                                                                                              
Notify: PPI Guid: 49EDB1C1-BF21-4761-BB12-EB0031AABB39, Peim notify entry point: 9000000090126BA0                                                                                              
The 1th FV start address is 0x90000000C00C0000, size is 0x00280000, handle is 0x90000000C00C0000                                                                                               
Found firmware volume Image File 90000000C00C0048 in FV[1] 90000000C00C0000                                                                                                                    
PROGRESS CODE: V03020003 I0                                                                                                                                                                    
Temp Stack : BaseAddress=0x9000000090300000 Length=0x100000                                                                                                                                    
Temp Heap  : BaseAddress=0x9000000090200000 Length=0x100000                                                                                                                                    
Total temporary memory:    2097152 bytes.                                                                                                                                                      
  temporary memory stack ever used:       1048576 bytes.                                                                                                                                       
  temporary memory heap used for HobList: 24776 bytes.                                                                                                                                         
  temporary memory heap occupied by memory pages: 8192 bytes.                                                                                                                                  
Memory Allocation 0x00000004 0x90000000902FE000 - 0x90000000902FFFFF                                                                                                                           
Memory Allocation 0x00000004 0x90000000C0040000 - 0x90000000C011FFFF                                                                                                                           
Memory Allocation 0x00000004 0x90000000C0120000 - 0x90000000C0C1FFFF                                                                                                                           
Memory Allocation 0x0000000A 0x9000000090200000 - 0x90000000903FFFFF                                                                                                                           
Memory Allocation 0x0000000A 0x90000000C0000000 - 0x90000000C001FFFF                                                                                                                           
Old Stack size 1048576, New stack size 1048576                                                                                                                                                 
Stack Hob: BaseAddress=0x90000000C0C20000 Length=0x100000                                                                                                                                      
Heap Offset = 0x30B20000 Stack Offset = 0x30920000                                                                                                                                             
TemporaryRamMigration(0x9000000090200000, 0x90000000C0C20000, 0x200000)                                                                                                                        
        NewHeap created successfully, NewHeap Range: (0x90000000C0D20000 - 0x90000000C0E20000)                                                                                                 
        NewStack created successfully, NewStack Range: (0x90000000C0C20000 - 0x90000000C0D20000)                                                                                               
        Sp OldPoint 0x900000009037F878, NewPoint 0x90000000C0C9F878                                                                                                                            
Pages Offset = 0x6ED00000                                                                                                                                                                      
Loading PEIM at 0x90000000FEFE8000 EntryPoint=0x90000000FEFE8240 PeiCore.efi                                                                                                                   
Reinstall PPI: 8C8CE578-8A3D-4F1C-9935-896185C32DD3                                                                                                                                            
Reinstall PPI: 5473C07A-3DCB-4DCA-BD6F-1E9689E7349A                                                                                                                                            
Reinstall PPI: B9E0ABFE-5979-4914-977F-6DEE78C278A6                                                                                                                                            
Install PPI: F894643D-C449-42D1-8EA8-85BDD8C65BDE                                                                                                                                              
Loading PEIM at 0x90000000FEFDE000 EntryPoint=0x90000000FEFDE240 CapsulePei.efi                                                                                                                
PROGRESS CODE: V03020002 I0                                                                                                                                                                    
Install PPI: 3ACF33EE-D892-40F4-A2FC-3854D2E1323D                                                                                                                                              
PROGRESS CODE: V03020003 I0                                                                                                                                                                    
Loading PEIM at 0x90000000FEFD2000 EntryPoint=0x90000000FEFD2240 DxeIpl.efi                                                                                                                    
PROGRESS CODE: V03020002 I0                                                                                                                                                                    
PROGRESS CODE: V03020003 I0                                                                                                                                                                    
Install PPI: EE4E5898-3914-4259-9D6E-DC7BD79403CF                                                                                                                                              
Install PPI: 1A36E4E7-FAB6-476A-8E75-695A0576FDD7                                                                                                                                              
Install PPI: 0AE8CE5D-E448-4437-A8D7-EBF5F194F731                                                                                                                                              
Customized Guided section Memory Size required is 0xB00010 and address is 0x90000000FE4C1000                                                                                                   
Extract guided section Failed - Invalid Parameter                                                                                                                                              
Customized Guided section Memory Size required is 0xB00010 and address is 0x90000000FD9B0000                                                                                                   
Extract guided section Failed - Invalid Parameter                                                                                                                                              
Customized Guided section Memory Size required is 0xB00010 and address is 0x90000000FCE9F000                                                                                                   
Extract guided section Failed - Invalid Parameter                                                                                                                                              
Customized Guided section Memory Size required is 0xB00010 and address is 0x90000000FC38E000                                                                                                   
Extract guided section Failed - Invalid Parameter                                                                                                                                              
DXE IPL Entry                                                                                                                                                                                  
PROGRESS CODE: V03031000 I0                                                                                                                                                                    
                                                                                                                                                                                               
ASSERT_EFI_ERROR (Status = Not Found)                                                                                                                                                          
ASSERT [DxeIpl] /home/mengxiangdong/new/UEFI/uefi-sz/MdeModulePkg/Core/DxeIplPeim/DxeLoad.c(469): !EFI_ERROR (Status)

**Comment by MarsDoge** [comment]
rom烧写不完整，需要去确定烧录的电平是3.3还是1.8v.

**Comment by lshw** [comment]
确实是rom烧写不完整，我原来备份的rom不对，
不过也发现这里的fd文件， 直接用写片机写到rom里， 是不能启动的。

**Comment by lshw** [comment]
刷了个4.0.5569-stable202308的rom ， 好了

**Comment by lshw** [comment]
4.0.05569不行，还是黑屏，
4.0.05536可以了。
