### ISSUE TITLE
希望串口控制能更完善一些

### ISSUE THREAD

**Issue by lshw** [loongson/Firmware#65]
现在的串口可以代替键盘做输入， 但是完全是盲敲，回应在串口上没有，只显示在屏幕上，
如果ansi的屏幕控制比较麻烦， 或者只让uefi的shell 能够在串口工作， 也很好， 对于远程维护和远程安装系统，帮助很大。

**Comment by MarsDoge** [comment]
目前方案：
在连接1080p显示器时，为了缓解高分辨率与串口同步输出抢资源的问题，会自动隐藏Shell及UI串口输出.
你可以进入图形化的Shell: 输入 **mode 100 31** 来临时开启串口Shell. 
或者建议在不连接显示器的情况下，是不会隐藏串口输出的， 以上输入均不影响, 后续版本会针对该Issue进行优化.

**Comment by lshw** [comment]
看来是我不会用，不接显示器， 然后把语言设置为英文， 确实是串口可以完美操作了，谢谢。
如果不接显示器， 那么就自动切换为英文会更方便.
