### ISSUE TITLE
 3A6000 安装RX6750XT显卡，显示器无法显示BIOS界面，鼠标键盘也没有任何反应

### ISSUE THREAD

**Issue by tattocau** [loongson/Firmware#72]
3A6000 安装RX6750XT显卡，显示器无法显示BIOS界面，鼠标键盘也没有任何反应

**Comment by xry111** [comment]
我装上 RX550 (640 SP) 后也有这种现象。然后把内存都拔掉，不带内存开一次机，过十几秒后彻底断电再重插内存，之后好像就能正常引导了。

不知道是否适用于 RX 6000 系列。
