### ISSUE TITLE
ML5A_MB(L5A1) stable202305固件安装景嘉微jm7201显卡，点不亮，主板也无提示音（但还是能进系统），但换用R520显卡正常，依然无主板提示音

### ISSUE THREAD

**Issue by zhpascal** [loongson/Firmware#75]
3A5000的L5A1主板，升级ML5A_MB(L5A1) stable202305固件，用景嘉微jm7201显卡，开机点不亮，主板也无提示音（但黑屏许久后，还是能进系统），但换用R520显卡能正常现实loognix龙芯logon，能正常使用，但主板依然无提示音

**Comment by MarsDoge** [comment]
L5A1主板的BIOS不提供景嘉微显卡驱动，不影响系统启动暂不计划支持.
