### ISSUE TITLE
 天创者主板是否支持风扇动态调速

### ISSUE THREAD

**Issue by haowuge** [loongson/Firmware#77]
您好，我看天创者主板上主风扇是4针的，该风扇是否支持为动态调整转速？是固件暂时未支持？谢谢

**Comment by MarsDoge** [comment]
正式版stable202311支持，需要打开DVFS选项

**Comment by FanFansfan** [comment]
同问一下，发版了吗？202311的pcie兼容性似乎好点，从3a6000的测试上看，希望3a5000也更新一下。
