### ISSUE TITLE
Wonder about my motherboard type

### ISSUE THREAD

**Issue by jkxing** [loongson/Firmware#8]
My motherboard looks like ML5A, but board information shown in the system looks more like L5BMB01-CRB. I don't know which firmware suits my board.
![IMG_20220712_150437_1](https://user-images.githubusercontent.com/17963015/178430250-42b92188-2faa-4b8b-bb0e-f711e90980b0.jpg)
![IMG_20220712_145629](https://user-images.githubusercontent.com/17963015/178430267-d7ce2745-59ae-4649-96c5-12ba90b4678b.jpg)

**Comment by kilaterlee** [comment]
You can use the ML5A firmware, the SMBIOS information is wrong, I guess this BIOS is not from original factory. It is recommended to store current BIOS binary before updating.

**Comment by jkxing** [comment]
ML5A firmware works fine. Thanks
