### ISSUE TITLE
请求增加3C5000工作站主板固件支持

### ISSUE THREAD

**Issue by Xinmudotmoe** [loongson/Firmware#80]
处理器 LS3C5000 单路2.2GHz主频
散热器 A14-4881-1富其扬
主板 LS3C5000单路服务器主板 TC512A0 V1.1 主板 （含CPU散热器底座，7A2000桥片）
BMC卡 AST2500 BMC

**Comment by Xinmudotmoe** [comment]
> 请确认BIOS下是否有LegacyMode选项，如有，请关闭即可支持上游内核.

你好，存在LegacyMode选项的。希望可以支持 如 关闭x86emu 的新功能。

**Comment by xry111** [comment]
> > 请确认BIOS下是否有LegacyMode选项，如有，请关闭即可支持上游内核.
> 
> 你好，存在LegacyMode选项的。希望可以支持 如 关闭x86emu 的新功能。

我记得 x86emu 爆炸是 3A6000 的新现象，虽然目前根本原因还没完全查明。

3C5000 也会炸吗？

**Comment by MarsDoge** [comment]
> > > 请确认BIOS下是否有LegacyMode选项，如有，请关闭即可支持上游内核.
> > 
> > 
> > 你好，存在LegacyMode选项的。希望可以支持 如 关闭x86emu 的新功能。
> 
> 我记得 x86emu 爆炸是 3A6000 的新现象，虽然目前根本原因还没完全查明。
> 
> 3C5000 也会炸吗？

这个不区分芯片，GPU的模拟行为是个LA通用的需求.

**Comment by xry111** [comment]
> > > > 请确认BIOS下是否有LegacyMode选项，如有，请关闭即可支持上游内核.
> > > 
> > > 
> > > 你好，存在LegacyMode选项的。希望可以支持 如 关闭x86emu 的新功能。
> > 
> > 
> > 我记得 x86emu 爆炸是 3A6000 的新现象，虽然目前根本原因还没完全查明。
> > 3C5000 也会炸吗？
> 
> 这个不区分芯片，GPU的模拟行为是个LA通用的需求.

我记得前天线下讨论的时候说 RDNA 卡在 3A5000 的板子上能正常点亮，但是在 3A6000 板子上就必须关掉 x86emu (?)。

**Comment by MarsDoge** [comment]
> > > > > 请确认BIOS下是否有LegacyMode选项，如有，请关闭即可支持上游内核.
> > > > 
> > > > 
> > > > 你好，存在LegacyMode选项的。希望可以支持 如 关闭x86emu 的新功能。
> > > 
> > > 
> > > 我记得 x86emu 爆炸是 3A6000 的新现象，虽然目前根本原因还没完全查明。
> > > 3C5000 也会炸吗？
> > 
> > 
> > 这个不区分芯片，GPU的模拟行为是个LA通用的需求.
> 
> 我记得前天线下讨论的时候说 RDNA 卡在 3A5000 的板子上能正常点亮，但是在 3A6000 板子上就必须关掉 x86emu (?)。

固件下不能亮的，当初是针对性跳过进系统的吧？

**Comment by Xinmudotmoe** [comment]
经过学习~~摸鱼~~,成功在无选项的情况下禁用~~删除~~了x86emu. 可以摆脱"献祭流",直接使用rx5000+显卡直接启动.
使用了LongSoft/UEFITool移除了多项DXE driver.
```text
78CF1922-CE42-4734-BC70-991B6E83A94F Ls2k500GraphicsOutput
434AD1E6-47B7-A3CD-AFD3-97F80E5AB235 ASpeedAst2x00GopDxe
12AEDDCA-2A85-4D0C-B9E2-994EA4CD66D0 x86emu
9B036D6D-83EF-4D05-8DDF-018078537DA3 BiosVideo
CCCB0C28-4B24-11D5-9A5A-0090273FC14D GraphicsConsoleDxe
B88F4DA7-0A93-A5DE-ACF3-D97BA279A4AB PrimaryDisplayDxe
96D9682C-D3BB-4226-B0E1-FFE60C1DE65A PrimaryDisplayInit
6615943D-31D5-4B8B-B26C-24FB61B1DAC9 DetectBmcDxe
```
鉴于问题已经有缓解方式,我想可以关闭这个问题.
