### ISSUE TITLE
3A5000主板更新bios后开机十几秒才显示画面

### ISSUE THREAD

**Issue by singoo2012** [loongson/Firmware#94]
3A5000主板更新bios后开机十几秒才显示开机画面
主板型号：ML5A_MB_LL
芯片组：LS3A5000+7A1000
更新前使用昆仑固件
更新文件为UDK2018-LoongArch-ML5A-V4.0.05170-stable202305-Gmem-dbg

**Comment by MarsDoge** [comment]
@singoo2012 使用如下版本可以有效提升开启速度：UDK2018-LoongArch-ML5A-stable2408_Gmem_rel.fd
sha256: b038b525b21295e2f5c710dd43b585bc821ef8da0bf69659da23dc18c7b2ae46
